### ISSUE TITLE
Zed 1.0 Does Not Exist

### ISSUE THREAD

**Issue by nanohaddad** [Myzhar/ros_zed_cuda_driver#2]
Looking through the StereoLabs website, the latest SDK Release i've found is 0.9.1- yet this package, along with many others, depend on 1.0. 
While hardcoding 0.9.1 in place of 1.0 seems to complete CMake with no errors, I'm not sure it's the right method. 
Can anyone point me to the right SDK? 
Thanks ahead of time!

**Comment by Myzhar** [comment]
I noticed the same yesterday. I could not figure out why they put "1.0"
instead 0.91 that is their latest available version... I'm going to check.

## 

Walter Lucetti

email: myzhar@gmail.com
web: www.robot-home.it - www.opencv.it
project:  http://myzharbot.robot-home.it
Il 16/Ott/2015 00:52, "nanohaddad" notifications@github.com ha scritto:

**Comment by rnunziata** [comment]
Same for me....how to proceed?

```

CMake Error at ros_zed_cuda_driver/CMakeLists.txt:52 (find_package):
  Could not find a configuration file for package "ZED" that is compatible
  with requested version "1.0".

  The following configuration files were considered but not accepted:

    /usr/local/zed/zed-config.cmake, version: 0.9.2
    /usr/local/zed/zed-config.cmake, version: 0.9.2


```

**Comment by Myzhar** [comment]
Solved
